### ISSUE TITLE
Streetview broken

### ISSUE THREAD

**Issue by pascalpuffke** [spider-hand/Geoguess-Master-Web#14]
This only happens since today. The colors are inverted and it shows "For development purposes only" in the middle of the screen.
![Screenshot_20200629_172211](https://user-images.githubusercontent.com/30622888/86024455-4c9eed80-ba2d-11ea-9aaa-2c343d8ac74f.png)

**Comment by spider-hand** [comment]
Hey please read the limitation section on the home page. 

> Currently I set quotas per day so the cost to run this game can't get too high. If the map doesn't load, it means the quotas has been exceeded on the day. It will reset at midnight Pacific Time. Sorry for inconvenience. This game is open source so you can build your own game server and play this game unlimitedly.
