### ISSUE TITLE
Memory leak issue

### ISSUE THREAD

**Issue by Steccah** [spider-hand/Geoguess-Master-Web#27]
I don't know why but after 2 hours playing firefox ram usage was 12GB. After some time my system freezed

**Comment by spider-hand** [comment]
Hi thanks for reporting. I will investigate the issue soon. You can also clone this repo and run this game locally so I would really appreciate if you can figure out how to fix it by yourself.

**Comment by spider-hand** [comment]
Were you playing multiplayer games or only single player games then?

**Comment by Steccah** [comment]
Multiplayer, my two firends had the same issue, but with much less ram usage, one of 4GB an the other of 3GB, wich is a lot anyway. They were using chrome

**Comment by Steccah** [comment]
I played in the last months and it didn't happen anymore
