### ISSUE TITLE
Colors are inverted

### ISSUE THREAD

**Issue by vgaspary** [spider-hand/Geoguess-Master-Web#30]
The colors in Street View are inverted, and both Street View and Map (on the bottom left) show _"The page can't load Google Maps correctly."_ on startup.

Find the [screenshot](https://drive.google.com/file/d/1hbWkI-NdKEMi8B4T64rQ-oH4VMWLlyJR/view?usp=sharing).

**Comment by DerDomml** [comment]
I am having this issue as well. Did you find a solution for this?
