### ISSUE TITLE
Colors in chrome is inverse

### ISSUE THREAD

**Issue by KerteszDomokos** [spider-hand/Geoguess-Master-Web#33]
In the chrome, colours are inverse, here is an example:  

![example](https://user-images.githubusercontent.com/61547063/110325482-b1c4cd00-8017-11eb-867a-98e18e7c5fee.JPG)

In MS Edge or Mozzilla firefox sometimes are good the imaging, but not all times.

My English isn't perfect, sorry.

**Comment by spider-hand** [comment]
I already explained the reason on the website. Please read that.
