### ISSUE TITLE
Need more docs for noobs

### ISSUE THREAD

**Issue by gnouts** [spider-hand/Geoguess-Master-Web#8]
Hi,
This project looks really cool but I'm a total noob with GCP. Do you think you can make a more in-depth documentation for get all those API keys ? I can't actually test it because I'm lost in GCP console... :/

Maybe explain what they are use for and will I get charge at some time if I make a lot of requests ?

**Comment by spider-hand** [comment]
Hello I understand you but unfortunately this page is not for tutorial so I will not write in details. 
Please follow [this instruction](https://developers.google.com/maps/documentation/javascript/get-api-key#get-the-api-key) to get your own API key. For pricing, see [this](https://developers.google.com/maps/documentation/javascript/usage-and-billing). This explains how to set daily quota limits as well. But I think you don't have to worry about cost if you just play personally (or maybe with your friends).

**Comment by spider-hand** [comment]
Hey I will actually create another documentation so more people can follow the steps.

**Comment by spider-hand** [comment]
Sorry it's extremely late but now I added step-by-step instructions on Readme. Hope this helps for non developers.
